version: '3.8'

services:
  gateway-app:
    image: gateway-app:latest
    build:
      context: ./microservices/gateway
    container_name: gateway-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - category-app
      - elements-app
  
  category-app:
    image: category-app:latest
    build:
      context: ./microservices/profession-management-service
    container_name: category-app
    depends_on:
      - mysql-category
    environment:
      MYSQL_HOST: mysql-category
      MYSQL_PORT: 3306
    ports:
      - "8081:8081"
    networks:
      - app-network

  elements-app:
    image: elements-app:latest
    build:
      context: ./microservices/character-management-service
    container_name: elements-app
    depends_on:
      - mysql-elements
    environment:
      MYSQL_HOST: mysql-elements
      MYSQL_PORT: 3306
    ports:
      - "8082:8082"
    networks:
      - app-network

  angular-app:
    image: angular-app:latest
    build:
      context: ./auiApp
    container_name: angular-app
    ports:
      - "4200:80"
    networks:
      - app-network

  mysql-elements:
    image: mysql:8.0
    container_name: mysql-elements
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: AUILab-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_elements_data:/var/lib/mysql
    networks:
      - app-network

  mysql-category:
    image: mysql:8.0
    container_name: mysql-category
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: AUILab-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_category_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_elements_data:
  mysql_category_data:

networks:
  app-network:
    driver: bridge